service: musicapp

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  timeout: 30
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/*"
  logs:
    restApi: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
      - http:
          path: /register
          method: any
          cors: true
      - http:
          path: /home
          method: any
          cors: true
      - http:
          path: /home/query
          method: any
          cors: true
      - http:
          path: /home/subscribe
          method: any
          cors: true
      - http:
          path: /home/remove
          method: any
          cors: true
      - http:
          path: /home/logout
          method: any
          cors: true


plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    useStaticCache: true
    useDownloadCache: true
    usePoetry: false
    dockerizePip: true

